web:
  build: .
  #command: gunicorn budget_proj.wsgi:application -b :8000
  #command: python3 budget_proj/manage.py runserver
  command: /code/docker-entrypoint.sh
  volumes:
    - .:/code
  ports:
    - "8000:8000"
