# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_document', models.CharField(default='', max_length=255)),
                ('service_area', models.CharField(default='', max_length=255)),
                ('bureau', models.CharField(default='', max_length=255)),
                ('key_performance_measures', models.CharField(default='', max_length=255)),
                ('fy', models.CharField(default='', max_length=255)),
                ('budget_type', models.CharField(default='', max_length=255)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('units', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OCRB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_document', models.CharField(default='', max_length=255)),
                ('service_area', models.CharField(default='', max_length=255)),
                ('bureau', models.CharField(default='', max_length=255)),
                ('budget_category', models.CharField(default='', max_length=255)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('fy', models.CharField(default='', max_length=255)),
                ('budget_type', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
