# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_auto_20170221_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_center_code', models.CharField(default='', max_length=32)),
                ('fund_code', models.CharField(default='', max_length=32)),
                ('functional_area_code', models.CharField(default='', max_length=32)),
                ('object_code', models.CharField(default='', max_length=32)),
                ('fund_center_name', models.CharField(default='', max_length=255)),
                ('fund_name', models.CharField(default='', max_length=255)),
                ('functional_area_name', models.CharField(default='', max_length=255)),
                ('accounting_object_name', models.CharField(default='', max_length=255)),
                ('service_area_code', models.CharField(default='', max_length=32)),
                ('program_code', models.CharField(default='', max_length=32)),
                ('sub_program_code', models.CharField(default='', max_length=32)),
                ('fund_center', models.CharField(default='', max_length=32)),
                ('division_code', models.CharField(default='', max_length=32)),
                ('bureau_code', models.CharField(default='', max_length=32)),
                ('bureau_name', models.CharField(default='', max_length=255)),
                ('fiscal_year', models.CharField(default='', max_length=32)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
