# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_lookupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgethistory',
            name='service_area',
            field=models.ForeignKey(default=1554, on_delete=django.db.models.deletion.CASCADE, to='budget_app.LookupCode'),
            preserve_default=False,
        ),
    ]
