# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_lookupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgethistory',
            name='fiscal_year',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='kpm',
            name='fy',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrb',
            name='fy',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
