# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_auto_20170418_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgethistory',
            name='accounting_object_name',
            field=models.CharField(db_index=True, default='', help_text='Full name of a general accounting category corresponding to an object_code, such as "Internal Material and Services".', max_length=255),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='bureau_code',
            field=models.CharField(db_index=True, default='', help_text='2-character ID for a Bureau, e.g. "PS" for Public Safety.', max_length=32),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='bureau_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='fiscal_year',
            field=models.CharField(db_index=True, default='', help_text='Fiscal Year as a string, e.g. 2015-16.', max_length=32),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='functional_area_name',
            field=models.CharField(db_index=True, default='', help_text='Name for a functional area corresponding to a functional_area_code within a bureau, e.g. "Aquatics".', max_length=255),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='object_code',
            field=models.CharField(db_index=True, default='', help_text='Short string ID for a general accounting category, e.g. "EMS" for External Material and Services or "CAPITAL" for Capital Expenditures.', max_length=32),
        ),
        migrations.AlterField(
            model_name='budgethistory',
            name='service_area_code',
            field=models.CharField(db_index=True, default='', help_text='2-character ID [CD, LA, PR, PS, PU, TP] for a Service Area, which is a grouping of related Bureaus.', max_length=32),
        ),
        migrations.AlterField(
            model_name='kpm',
            name='fy',
            field=models.CharField(db_index=True, default='', help_text='Fiscal year (i.e. 2015-16)', max_length=255),
        ),
        migrations.AlterField(
            model_name='lookupcode',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='lookupcode',
            name='code_type',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='lookupcode',
            name='description',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrb',
            name='budget_category',
            field=models.CharField(db_index=True, default='', help_text='General category for this amount, which is one of [Capital, Operating].', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrb',
            name='budget_type',
            field=models.CharField(db_index=True, default='', help_text='Status of an item within the budget lifecycle: [Adopted, Revised, Actual].', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrb',
            name='bureau',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrb',
            name='fy',
            field=models.CharField(db_index=True, default='', help_text='Fiscal Year as a string, e.g. 2015-16', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrb',
            name='service_area',
            field=models.CharField(db_index=True, default='', help_text='Name of a Service Area, which is a grouping of related Bureaus.', max_length=255),
        ),
    ]
