# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_index_and_alphabetize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpm',
            old_name='fy',
            new_name='fiscal_year',
        ),
        migrations.RenameField(
            model_name='ocrb',
            old_name='fy',
            new_name='fiscal_year',
        ),
    ]
